
extern _Bool carry_flag;
extern _Bool borrow_flag;
extern unsigned char mod;
extern unsigned char high;

extern unsigned char tl1_mem[256*256];
void tl1_putch(unsigned char ch);
void tl1_io_init(void);
void tl1_io_finalize(void);
void tl1_putstr(char* str);
void tl1_putnum(unsigned char x);
void tl1_puthex(unsigned char x);
void tl1_putright(unsigned char c, unsigned char x);
unsigned char tl1_adc(unsigned char x, unsigned char y);
unsigned char tl1_sbc(unsigned char x, unsigned char y);
unsigned char tl1_eor(unsigned char x, unsigned char y);
unsigned char tl1_or(unsigned char x, unsigned char y);
unsigned char tl1_and(unsigned char x, unsigned char y);
unsigned char tl1_gt(unsigned char x, unsigned char y);
unsigned char tl1_lt(unsigned char x, unsigned char y);
unsigned char tl1_ugt(unsigned char x, unsigned char y);
unsigned char tl1_ult(unsigned char x, unsigned char y);
unsigned char tl1_diff(unsigned char x, unsigned char y);
unsigned char tl1_eq(unsigned char x, unsigned char y);
unsigned char tl1_plus(unsigned char x, unsigned char y);
unsigned char tl1_minus(unsigned char x, unsigned char y);
unsigned char tl1_mul(unsigned char x, unsigned char y);
unsigned char tl1_div(unsigned char x, unsigned char y);
void tl1_stop(void);
unsigned char f_mod_sys(void);
unsigned char f_get_sys(unsigned char x);
unsigned char f_mhigh_sys(void);
unsigned char f_mod_sys(void);
unsigned char f_mhigh_sys(void);
unsigned char f_rnd_sys(unsigned char x);
unsigned char f_not_sys(unsigned char x);
unsigned char f_neg_sys(unsigned char x);
unsigned char f_com_sys(unsigned char x);
unsigned char f_lsr_sys(unsigned char x);
unsigned char f_asr_sys(unsigned char x);
unsigned char f_asl_sys(unsigned char x);
unsigned char f_ror_sys(unsigned char x);
unsigned char f_rol_sys(unsigned char x);
